### ISSUE TITLE
Add .zsh_history support for latest macOS compatibility

### ISSUE THREAD

**Issue by ale-ben** [linonetwo/hyper-cli2gui#4]
macOS Catalina switched the default terminal from bash to zsh, you should implement support for both .zsh_history and .bash_history.

I made a quick fix by editing dist/index.js and src/search/history.js and replacing every '.bash_history' with a '.zsh_history' but this is a workaround, it's not a fix

**Comment by linonetwo** [comment]
Solved in latest release.
